version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=ghost
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  ghost:
    image: ghost:3.22.1-alpine
    restart: unless-stopped
    ports:
    - "2368:2368"
    depends_on:
      - db
    environment:
      url: $GHOST_URL
      database__client: mysql
      database__connection__host: db
      database__connection__user: $MYSQL_USER
      database__connection__password: $MYSQL_PASSWORD
      database__connection__database: ghost
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - app-network

volumes:
  ghost_data:
  db_data:

networks:
  app-network:
    driver: bridge